#!/bin/bash
if [ -z "$1" ]; then
	echo "Usage: ./newtest <pkgname> [<command> <args>...]"
	exit 2
fi

pkgname="$1"
shift

if [ -e "tests/$pkgname" ]; then
	echo "File exists!"
	exit 3
fi

cat > "tests/$pkgname" <<- EOF
	#!/bin/bash
	set -v

EOF

echo "$@" >> "tests/$pkgname" || exit 4
chmod a+x "tests/$pkgname" || exit 5
