#!/bin/bash
# vi: set et sw=4 sts=4:
set -v

killall python
killall python2

python << EOF &
from twisted.web import server, resource
from twisted.internet import reactor, endpoints

class Counter(resource.Resource):
    isLeaf = True
    numberRequests = 0

    def render_GET(self, request):
        self.numberRequests += 1
        request.setHeader(b"content-type", b"text/plain")
        content = "It works!\n"
        return content.encode("ascii")

endpoints.serverFromString(reactor, "tcp:8080").listen(server.Site(Counter()))
reactor.run()
EOF

sleep 2
curl -s 'http://localhost:8080/' || (echo "It doesn't work!" && exit 1)
sleep 2
killall python

python2 << EOF &
from twisted.web import server, resource
from twisted.internet import reactor, endpoints

class Counter(resource.Resource):
    isLeaf = True
    numberRequests = 0

    def render_GET(self, request):
        self.numberRequests += 1
        request.setHeader(b"content-type", b"text/plain")
        content = u"It works!\n"
        return content.encode("ascii")

endpoints.serverFromString(reactor, "tcp:8080").listen(server.Site(Counter()))
reactor.run()
EOF

sleep 2
curl -s 'http://localhost:8080/' || (echo "It doesn't work!" && exit 1)
killall python2
